"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
import environ
from django.templatetags.static import static

# Chemin du projet
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger le .env
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, "core/.env"))

# Sécurité
SECRET_KEY = env("SECRET_KEY")

DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    # custom admin app
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",
    # base app
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "parler",
    "import_export",
    "ckeditor",
    "ckeditor_uploader",
    # custom app
    "landing",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


# Langue par défaut
LANGUAGE_CODE = "en"

# Liste des langues supportées
LANGUAGES = [
    ("fr", _("Français")),
    ("en", _("English")),
]

PARLER_LANGUAGES = {
    None: (
        {"code": "fr"},
        {"code": "en"},
    ),
    "default": {
        "fallbacks": ["fr"],  # fallback si pas de traduction
        "hide_untranslated": False,  # si True, cacher les objets sans traduction
    },
}

# Chemin pour les fichiers de traduction
LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# Activer internationalisation
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Time zone
TIME_ZONE = "UTC+1"

# Localization settings
USE_THOUSAND_SEPARATOR = True
NUMBER_GROUPING = 3


# Configuration Unfold
UNFOLD = {
    "SITE_TITLE": "Customs PACT 2025",
    "SITE_HEADER": "Customs PACT Administration",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("favicon.png"),
        "dark": lambda request: static("favicon.png"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("logo-light.png"),
        "dark": lambda request: static("logo-dark.png"),
    },
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Dashboard",
                "items": [
                    {
                        "title": "Overview",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Event Management",
                "collapsible": True,
                "items": [
                    {
                        "title": "Event Configuration",
                        "icon": "settings",
                        "link": "/admin/landing/eventconfiguration/",
                    },
                    {
                        "title": "About Section",
                        "icon": "info",
                        "link": "/admin/landing/aboutsection/",
                    },
                ],
            },
            {
                "title": "Program",
                "collapsible": True,
                "items": [
                    {
                        "title": "Speakers",
                        "icon": "group",
                        "link": "/admin/landing/speaker/",
                    },
                    {
                        "title": "Program Days",
                        "icon": "calendar_today",
                        "link": "/admin/landing/programday/",
                    },
                    {
                        "title": "Sessions",
                        "icon": "event",
                        "link": "/admin/landing/programsession/",
                    },
                ],
            },
            {
                "title": "Registrations",
                "collapsible": True,
                "items": [
                    {
                        "title": "All Registrations",
                        "icon": "how_to_reg",
                        "link": "/admin/landing/registration/",
                        "badge": lambda request: Registration.objects.filter(
                            status="pending"
                        ).count(),
                    },
                    {
                        "title": "Contact Messages",
                        "icon": "mail",
                        "link": "/admin/landing/contactmessage/",
                        "badge": lambda request: ContactMessage.objects.filter(
                            is_read=False
                        ).count(),
                    },
                ],
            },
            {
                "title": "Logistics",
                "collapsible": True,
                "items": [
                    {
                        "title": "Venues",
                        "icon": "place",
                        "link": "/admin/landing/venue/",
                    },
                    {
                        "title": "Hotels",
                        "icon": "hotel",
                        "link": "/admin/landing/hotel/",
                    },
                    {
                        "title": "Logistic Info",
                        "icon": "local_shipping",
                        "link": "/admin/landing/logisticinfo/",
                    },
                ],
            },
            {
                "title": "Partners & Media",
                "collapsible": True,
                "items": [
                    {
                        "title": "Partners",
                        "icon": "handshake",
                        "link": "/admin/landing/partner/",
                    },
                    {
                        "title": "Contacts",
                        "icon": "contact_phone",
                        "link": "/admin/landing/contact/",
                    },
                ],
            },
        ],
    },
}


# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "full",
        "height": 300,
        "width": "100%",
    },
}

# Email Configuration (exemple avec SendGrid)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "apikey"
EMAIL_HOST_PASSWORD = env("SENDGRID_API_KEY")
DEFAULT_FROM_EMAIL = "noreply@customspact.org"

# Import/Export
IMPORT_EXPORT_USE_TRANSACTIONS = True


# # Email settings
# EMAIL_BACKEND = env(
#     "EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend"
# )
# EMAIL_HOST = env("EMAIL_HOST", default="")
# EMAIL_PORT = env.int("EMAIL_PORT", default=587)
# EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
# EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
# EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
# CONTACT_EMAIL = env("CONTACT_EMAIL", default="")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "assets",
    BASE_DIR / "css",
    BASE_DIR / "js",
]
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

if os.environ.get("ENV") == "PRODUCTION":

    # Static files settings
    PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

    STATIC_ROOT = os.path.join(PROJECT_ROOT, "staticfiles")

    # Extra places for collectstatic to find static files.
    STATICFILES_DIRS = (os.path.join(PROJECT_ROOT, "static"),)

    # Simplified static file serving.
    # https://warehouse.python.org/project/whitenoise/
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

    # DATABASES = { 'default': dj_database_url.config(conn_max_age=500) }
